[project]
name = 'Science-Funding-DAO-Platform'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.milestone-funding-escrow]
path = 'contracts/milestone-funding-escrow.clar'
clarity_version = 3
epoch = '3.2'

[contracts.open-data-verification]
path = 'contracts/open-data-verification.clar'
clarity_version = 3
epoch = 'latest'

[contracts.peer-review-consensus]
path = 'contracts/peer-review-consensus.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
